<?php
function getTeamName($teamId)
	{
		$innerHTML = "";
		try
		{
			$html = getHTML("http://pesstatsdatabase.com/PSD/Players.php?Club=".intval($teamId));
			$dom = new DOMDocument;
			$dom->loadHTML($html);
			$xpath = new DOMXPath($dom);

			$nodes = $xpath->query("//*[contains(concat(' ', normalize-space(@class), ' '), 'tb_psd')]//tr//td//img");
			if ($nodes->length > 0)
			{
				$teamName = str_replace("-"," ",str_replace(".png","",end(explode("/",$nodes[0]->getAttribute("src")))));
				$innerHTML .= $teamId." => \"".$teamName."\"\n";
			}
		}
		catch(Exception $e) {}
		return $innerHTML;
	}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Hardcoded part (since there is no way we can put this into api)
// generated using:
/*

ob_start();
ob_implicit_flush(true);
@ini_set('zlib.output_compression',0);
@ini_set('implicit_flush',1);
@ob_end_clean();
set_time_limit(0);
	for ($i=0; $i<=482; $i++)
	{
		echo getTeamName($i);	
		ob_flush();
	}
*/
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
$teamNames = array(
0 => "Retired Players",
1 => "Arsenal FC",
2 => "Aston Villa FC",
3 => "Birmingham City FC",
4 => "Bolton Wanderers FC",
7 => "Chelsea FC",
8 => "Everton FC",
9 => "Fulham FC",
10 => "Liverpool FC",
11 => "Manchester City FC",
12 => "Manchester United FC",
13 => "Newcastle United FC",
14 => "Stoke City FC",
15 => "Sunderland AFC",
16 => "Tottenham Hotspur FC",
17 => "West Bromwich Albion FC",
18 => "West Ham United FC",
21 => "Athletic Club",
22 => "Club Atletico de Madrid",
23 => "CA Osasuna",
24 => "RC Deportivo La Coruna",
25 => "FC Barcelona",
26 => "Getafe CF",
28 => "Levante UD",
29 => "Malaga CF",
30 => "RCD Espanyol",
31 => "RCD Mallorca",
33 => "Real Madrid CF",
34 => "Real Sociedad de Futbol",
35 => "Real Zaragoza",
36 => "Sevilla FC",
37 => "Real Sporting de Gijon",
38 => "UD Almeria",
39 => "Valencia CF",
40 => "Villarreal CF",
41 => "AC Cesena",
42 => "AC ChievoVerona",
43 => "AC Milan",
44 => "ACF Fiorentina",
45 => "FC Bari 1908",
46 => "AS Roma",
47 => "Bologna FC 1909",
48 => "Brescia Calcio",
49 => "Cagliari Calcio",
51 => "FC Internazionale Milano",
52 => "Genoa CFC",
53 => "Juventus FC",
55 => "SS Lazio",
56 => "SSC Napoli",
57 => "UC Sampdoria",
58 => "US Citta di Palermo",
60 => "Udinese Calcio",
61 => "1. FC Kaiserslautern",
62 => "1. FC Koln",
63 => "1. FC Nurnberg",
64 => "1. FSV Mainz 05",
65 => "Bayer 04 Leverkusen",
66 => "Borussia Dortmund",
67 => "Borussia Monchengladbach",
68 => "Eintracht Frankfurt",
69 => "FC Bayern Munchen",
70 => "FC Schalke 04",
71 => "FC St. Pauli",
72 => "Hamburger SV",
73 => "Hannover 96",
74 => "SC Freiburg",
75 => "SV Werder Bremen",
76 => "TSG 1899 Hoffenheim",
77 => "VfB Stuttgart",
78 => "VfL Wolfsburg",
98 => "AJ Auxerre",
99 => "AS Monaco FC",
100 => "AS Nancy",
101 => "AS Saint Etienne",
102 => "FC Girondins de Bordeaux",
103 => "FC Lorient",
105 => "Lille OSC",
106 => "Montpellier HSC",
107 => "OGC Nice",
108 => "Olympique Lyonnais",
109 => "Olympique de Marseille",
110 => "Paris Saint Germain FC",
111 => "RC Lens",
112 => "SM Caen",
113 => "Stade Brestois 29",
114 => "Stade Rennais FC",
115 => "Toulouse FC",
116 => "Valenciennes FC",
120 => "FC Dinamo Moskva",
122 => "FC Lokomotiv Moskva",
124 => "FC Rubin Kazan",
127 => "FC Spartak Moskva",
130 => "FC Zenit",
131 => "PFC CSKA Moskva",
135 => "FC CFR 1907 Cluj",
136 => "CS Gaz Metan Mediaș",
137 => "CS Pandurii Târgu Jiu",
138 => "AFC Astra Giurgiu",
140 => "FC Dinamo București",
143 => "FCSB",
144 => "ACS Poli Timişoara",
149 => "ASA Tîrgu Mureș",
153 => "CS Maritimo",
154 => "FC Pacos de Ferreira",
155 => "FC Porto",
158 => "Rio Ave FC",
160 => "SC Braga",
162 => "SL Benfica",
163 => "Sporting Clube de Portugal",
165 => "Vitoria de Guimaraes",
166 => "Vitoria de Setubal",
169 => "Beşiktaş JK",
171 => "Bursaspor",
173 => "Fenerbahce SK",
174 => "Galatasaray AŞ",
184 => "Trabzonspor AŞ",
185 => "AEK Athens",
187 => "AOK Kerkyra",
188 => "Aris Thessaloniki FC",
189 => "Atromitos FC",
190 => "Ergotelis FC",
191 => "FC Asteras Tripolis",
193 => "AE Larisa",
194 => "Olympiacos FC",
196 => "PAOK",
197 => "Panathinaikos A.O.",
198 => "Panionios G.S.S.",
199 => "Panserraikos FC",
200 => "AO Xanthi",
201 => "ADO Den Haag",
202 => "AFC Ajax",
203 => "AZ Alkmaar",
204 => "De Graafschap",
205 => "SBV Excelsior",
206 => "FC Groningen",
207 => "FC Twente",
208 => "FC Utrecht",
209 => "Feyenoord",
210 => "Heracles Almelo",
211 => "NAC Breda",
212 => "NEC Nijmegen",
213 => "PSV Eindhoven",
214 => "Roda JC",
215 => "sc Heerenveen",
216 => "VVV Venlo",
217 => "Vitesse",
218 => "Willem II",
220 => "Celtic FC",
231 => "FC Red Bull Salzburg",
241 => "Arka Gdynia",
242 => "Cracovia Krakow",
244 => "Gornik Zabrze",
245 => "Jagiellonia Białystok",
246 => "Korona Kielce",
247 => "Lech Poznań",
248 => "Lechia Gdańsk",
249 => "Legia Warszawa",
252 => "Ruch Chorzow",
254 => "Wisla Krakow",
255 => "Zagłębie Lubin",
256 => "Śląsk Wrocław",
259 => "Botafogo FR",
260 => "CR Flamengo",
261 => "CR Vasco da Gama",
263 => "Atletico Mineiro",
264 => "Atletico Paranaense",
265 => "Cruzeiro EC",
266 => "EC Vitoria",
267 => "Fluminense FC",
268 => "Goias EC",
270 => "Grêmio FBPA",
272 => "SC Corinthians P",
273 => "SC Internacional",
274 => "Santos FC",
275 => "SE Palmeiras",
276 => "Sao Paulo FC",
277 => "Argentinos Juniors",
278 => "Arsenal de Sarandi",
279 => "All Boys",
280 => "Banfield",
281 => "Boca Juniors",
282 => "Huracan",
283 => "Independiente",
284 => "Lanus",
285 => "River Plate",
286 => "San Lorenzo ",
287 => "Tigre",
288 => "Velez Sarsfield",
289 => "Gimnasia de La Plata",
290 => "Colon de Santa Fe",
291 => "Estudiantes de La Plata",
292 => "Godoy Cruz Antonio Tomba",
293 => "Newells Old Boys",
294 => "Olimpo",
295 => "Quilmes",
296 => "Racing Club",
315 => "BSC Young Boys",
318 => "FC Basel",
320 => "FC Dynamo Kyiv",
323 => "FC Shakhtar Donetsk",
329 => "AC Sparta Praha",
335 => "Club Brugge KV",
336 => "FC København",
345 => "RSC Anderlecht",
346 => "Racing Genk FC",
350 => "Standard Liège",
352 => "AEL Limassol",
353 => "APOEL FC",
356 => "FK Partizan Belgrade",
359 => "FK Vojvodina",
360 => "HNK Hajduk Split",
362 => "GNK Dinamo Zagreb",
363 => "FK Crvena Zvezda",
364 => "_Other Clubs",
365 => "_Other Clubs",
366 => "_Other Clubs",
367 => "West Asia Players",
369 => "East Asia Players",
416 => "CAF Players",
419 => "CD Guadalajara",
421 => "Pumas de la UNAM",
422 => "Club America",
424 => "Cruz Azul",
430 => "_CONCACAF Players",
433 => "Universidad de Chile",
434 => "Penarol",
437 => "Nacional",
438 => "Colo Colo",
444 => "Universidad Catolica",
448 => "_Other Clubs",
449 => "Non Affiliated",
450 => "Atalanta BC",
452 => "Empoli FC",
456 => "US Sassuolo Calcio",
458 => "Torino FC",
460 => "Delfino Pescara 1936",
462 => "CD Numancia",
463 => "Real Valladolid CF",
464 => "Real Betis Balompie",
466 => "Hull City AFC",
467 => "Leicester City FC",
468 => "Queens Park Rangers FC",
470 => "AD Alcorcon",
473 => "RC Celta de Vigo",
474 => "Cordoba CF",
475 => "Elche CF",
477 => "Girona FC",
478 => "Granada CF",
480 => "UD Las Palmas",
482 => "Rayo Vallecano de Madrid"
);

?>
